server:
  listenurl: ":8080"
auth:
  key: "thisisatestkeyusedfordevelopmentpurposeonly"
logger:
  level: "DEBUG"
db:
  dialect: "sqlite3"
  sqlite:
    filename: "test.db"
worker:
  enabled: true
display:
  active_window_minutes: 15
  connection_window_minutes: 1440
  expected_interval_minutes: 5
  poor_connection_threshold: 0.8
  default_page_size: 50